apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-eks
  namespace: tekton-pipelines
spec:
  params:
    - name: ecr-repo
      type: string
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      script: |
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: demo-app
          namespace: default
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: demo-app
          template:
            metadata:
              labels:
                app: demo-app
            spec:
              containers:
              - name: demo-app
                image: $(params.ecr-repo):latest
                ports:
                - containerPort: 8080
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: demo-app
          namespace: default
        spec:
          selector:
            app: demo-app
          ports:
          - port: 80
            targetPort: 8080
          type: LoadBalancer
        EOF
