apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fossa-scan
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
    - name: scan
      image: fossa/fossa-cli:latest
      script: |
        cd $(workspaces.source.path)/source
        fossa analyze --api-key $(cat /tekton/creds/fossa-credentials/api-key)
      volumeMounts:
        - name: fossa-creds
          mountPath: /tekton/creds/fossa-credentials
          readOnly: true
  volumes:
    - name: fossa-creds
      secret:
        secretName: fossa-credentials
