apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: ./Basic-API/demo/Dockerfile
    - name: CONTEXT
      type: string
      default: ./Basic-API/demo
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ecr-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ecr-credentials
              key: AWS_SECRET_ACCESS_KEY
      script: |
        /kaniko/executor \
          --dockerfile $(params.DOCKERFILE) \
          --context $(workspaces.source.path)/source/$(params.CONTEXT) \
          --destination $(params.IMAGE)
