apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
    - name: maven-cache
  steps:
    - name: build
      image: maven:3.8-openjdk-17
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      script: |
        cd $(workspaces.source.path)/source/Basic-API/demo
        mvn -Dmaven.repo.local=$(workspaces.maven-cache.path) clean package
