apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scan
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
    - name: scan
      image: maven:3.8-openjdk-17
      script: |
        cd $(workspaces.source.path)/source
        mvn sonar:sonar -Dsonar.token=$(cat /tekton/creds/sonarqube-credentials/token)
      volumeMounts:
        - name: sonarqube-creds
          mountPath: /tekton/creds/sonarqube-credentials
          readOnly: true
  volumes:
    - name: sonarqube-creds
      secret:
        secretName: sonarqube-credentials
